import DS from 'ember-data';

export default DS.Model.extend({
  username: DS.attr(),
  password: DS.attr(),
  birthday: DS.attr(),
  zip_code: DS.attr(),
  country: DS.attr(),
  ethnicity: DS.attr(),
  status: DS.attr(),
  height: DS.attr(),
  body_type: DS.attr(),
  diet: DS.attr(),
  smoking: DS.attr(),
  drinking: DS.attr(),
  drugs: DS.attr(),
  spirituality: DS.attr(),
  education: DS.attr(),
  kids: DS.attr(),
  kink_friendly: DS.attr(),
  pets: DS.attr(),
  languages: DS.attr(),
  preferred_gender: DS.attr(),
  preferred_age: DS.attr(),
  preferred_relationship_type: DS.attr(),
  preferred_relationship_status: DS.attr(),
  preferred_distance: DS.attr(),
  about_me: DS.attr(),
  interests: DS.attr(),
  favorites: DS.attr(),
  island: DS.attr(),
  free_time: DS.attr(),
  images: DS.attr()
});
